### ISSUE TITLE
cmake error in ply_c

### ISSUE THREAD

**Issue by shobhitjdpsr** [loicland/superpoint_graph#138]
![booost](https://user-images.githubusercontent.com/20614765/61836025-f5b78e00-ae43-11e9-8207-ef9589f95639.png)
![boost](https://user-images.githubusercontent.com/20614765/61836026-f5b78e00-ae43-11e9-8354-538e5dbe24a9.png)
![boost2](https://user-images.githubusercontent.com/20614765/61836027-f6502480-ae43-11e9-82b6-597337eac958.png)
![cmake error](https://user-images.githubusercontent.com/20614765/61836028-f6502480-ae43-11e9-8cae-79d236c872f3.png)

While running cmake . -DPYTHON_LIBRARY=$CONDAENV/lib/libpython3.6m.so -DPYTHON_INCLUDE_DIR=$CONDAENV/include/python3.6m -DBOOST_INCLUDEDIR=$CONDAENV/include -DEIGEN3_INCLUDE_DIR=$CONDAENV/include/eigen3

I am getting an error that boost is too old, despite of installing boost 1.66.

What all can I do to make this work?

**Comment by shobhitjdpsr** [comment]
@loicland

**Comment by loicland** [comment]
Hi,

what did your set CONDAENV to?

and what is the results of 
```
conda list
```

in a terminal?

**Comment by shobhitjdpsr** [comment]
![conda](https://user-images.githubusercontent.com/20614765/61887168-b67e5100-aec6-11e9-8344-1db932956cee.png)

![temp](https://user-images.githubusercontent.com/20614765/61887200-cc8c1180-aec6-11e9-94d6-c5b6ef7d74f0.png)
 

@loicland   Please have a llook

**Comment by shobhitjdpsr** [comment]
@Pandinosaurus  @loicland

**Comment by loicland** [comment]
CONDAENV should be more like something like
/home/your_session/anaconda3

Find it by typing 
```locate anaconda```

**Comment by shobhitjdpsr** [comment]
@loicland 

Hi Thanks for input! 

After doing it I am getting further error:-
![abcd](https://user-images.githubusercontent.com/20614765/61900241-d28feb80-aee2-11e9-865a-72e6dc523e76.png)

**Comment by shobhitjdpsr** [comment]
@loicland 


![error](https://user-images.githubusercontent.com/20614765/61900540-77aac400-aee3-11e9-9a9a-6075a8252670.png)

**Comment by shobhitjdpsr** [comment]
@loicland 
![abcdddd](https://user-images.githubusercontent.com/20614765/61900694-be98b980-aee3-11e9-99ff-6f9618406ae7.png)

**Comment by shobhitjdpsr** [comment]
@loicland 
Never mind I got it working., by removing cmakecache.txt .

But next error is in make
![done](https://user-images.githubusercontent.com/20614765/61901255-f5230400-aee4-11e9-9458-b8ef8a3e1510.png)

**Comment by shobhitjdpsr** [comment]
In ply_c while doing MAKE, I am getting following error:

[ 50%] Building CXX object CMakeFiles/ply_c.dir/ply_c.cpp.o
/home/spartan/Desktop/superpoint_graph/partition/ply_c/ply_c.cpp:4:23: fatal error: Eigen/Dense: No such file or directory
 #include <Eigen/Dense>
                       ^
compilation terminated.
CMakeFiles/ply_c.dir/build.make:62: recipe for target 'CMakeFiles/ply_c.dir/ply_c.cpp.o' failed
make[2]: *** [CMakeFiles/ply_c.dir/ply_c.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ply_c.dir/all' failed
make[1]: *** [CMakeFiles/ply_c.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
(my_env) spartan@spartan-

**Comment by loicland** [comment]
Have you tried the latest commit? Otherwise reinstall Eigen.

**Comment by shobhitjdpsr** [comment]
I tried the commit which was there 24 hours ago approx

@loicland

**Comment by shobhitjdpsr** [comment]
@loicland 

SEE Eigen is already in newwst version, what should I try next?
![eigen](https://user-images.githubusercontent.com/20614765/61904072-b04e9b80-aeeb-11e9-9a8f-75d0ded07f0d.png)

**Comment by shobhitjdpsr** [comment]
@loicland 
Nevermind, This was fixed by editing partition/ply_c/ply_c.cpp and changing TO:-
#include <eigen3/Eigen/Dense>
#include <eigen3/Eigen/Eigenvalues








**BUT, NOW I AM GETTING FOLLOWING ISSUE:-

 fatal error: pyconfig.h: No such file or directory**
 



![pyconfig](https://user-images.githubusercontent.com/20614765/61905993-fc034400-aeef-11e9-9ab5-9b2d34b3418a.png)

**Comment by loicland** [comment]
Check whether your anaconda is using python3.6m, and if not adapt the cmake options (and dont forget to destroy all the cmakefiles).

**Comment by shobhitjdpsr** [comment]
Thanks, it worked, I changed to 3.7m in cmake, because thats what I had in my cmake

Now  @loicland 

cmake .. -DPYTHON_LIBRARY=$CONDAENV/lib/libpython3.7m.so -DPYTHON_INCLUDE_DIR=$CONDAENV/include/python3.7m -DBOOST_INCLUDEDIR=$CONDAENV/include -DEIGEN3_INCLUDE_DIR=$CONDAENV/include/eigen3


I am getting error
![hu](https://user-images.githubusercontent.com/20614765/61909548-12150280-aef8-11e9-959c-6181a9820754.png)

**Comment by shobhitjdpsr** [comment]
Just for your reference:-
![#123](https://user-images.githubusercontent.com/20614765/61912245-388a6c00-aeff-11e9-87fc-342bb63fb3f7.png)
![#1234](https://user-images.githubusercontent.com/20614765/61912246-388a6c00-aeff-11e9-90d5-89748a77d6c2.png)

**Comment by shobhitjdpsr** [comment]
@loicland 

Now I will summarize the whole problem that I am facing currently:-

While compiling libcp, and running cmake (cmake .. -DPYTHON_LIBRARY=$/home/spartan/anaconda3/lib/libpython3.7m.so -DPYTHON_INCLUDE_DIR=$/home/spartan/anaconda3/include/python3.7m -DBOOST_INCLUDEDIR=$/usr/local/lib -DEIGEN3_INCLUDE_DIR=$/home/spartan/anaconda3/include/eigen3
) 
Note:- I have python3.7m in my anaconda3/lib and it worked for ply_c

Now , I am getting the following errors:-
![errrrrrr](https://user-images.githubusercontent.com/20614765/61914919-e0a43300-af07-11e9-91ab-c5ef39e6a9de.png)

ALso while running locate libboost python, I am getting following errors:-

![#1](https://user-images.githubusercontent.com/20614765/61914984-29f48280-af08-11e9-83aa-e99413060c78.png)
![#2](https://user-images.githubusercontent.com/20614765/61914985-2a8d1900-af08-11e9-816c-f7d02c4f956c.png)
![#22](https://user-images.githubusercontent.com/20614765/61914998-38429e80-af08-11e9-8834-36b133f352fd.png)

**Comment by shobhitjdpsr** [comment]
@loicland 

What would you recommend to currently do in order to run cmake for cut_pursuit ???

(I am on Ubuntu 16.04)

**Comment by loicland** [comment]
you should remove the `$` before your anaconda path.

**Comment by shobhitjdpsr** [comment]
![see](https://user-images.githubusercontent.com/20614765/61963724-e0e91080-af91-11e9-8656-6d6ee5526c21.png)


@loicland 
Even after doing the same, I am still getting errors

**Comment by shobhitjdpsr** [comment]
![checkk](https://user-images.githubusercontent.com/20614765/61965452-dfb9e280-af95-11e9-897d-b13ac1491e63.png)

**Comment by loicland** [comment]
Have you tried the symbolic link fix I added today to the readme?

Otherwise replace in cut pursuit /sec/cmakeist
` numpy${PYTHONVERSION} `
By
    ` numpy `

**Comment by shobhitjdpsr** [comment]
![hiiii](https://user-images.githubusercontent.com/20614765/61967992-738ead00-af9c-11e9-8c1b-9a4b28bc01bb.png)


Do you mean just the line highlighted to be changed?

**Comment by shobhitjdpsr** [comment]
@loicland

**Comment by shobhitjdpsr** [comment]
![1](https://user-images.githubusercontent.com/20614765/61968305-4bec1480-af9d-11e9-9d1e-5f66d5bcfb99.png)
![abcd](https://user-images.githubusercontent.com/20614765/61968306-4bec1480-af9d-11e9-87da-14820e2f08bc.png)


@loicland 
I did try the new command in readme for symbolic link, but still I am getting and error. Should I change the cmakeLists also?

**Comment by loicland** [comment]
Anywhere bumpy appears. But try the symbolic link first.

And dont forget to remove makefiles etc... after the changes.

**Comment by shobhitjdpsr** [comment]
@loicland 

Do you mean to remove cmakecachefiles?

ALso on trying 
 cmake .. -DPYTHON_LIBRARY=/home/spartan/Anaconda3/envs/my_env/lib/libpython3.7m.so -DPYTHON_INCLUDE_DIR=/home/spartan/Anaconda3/envs/my_env/include/python3.7m -DBOOST_INCLUDEDIR=/home/spartan/Anaconda3/include -DEIGEN3_INCLUDE_DIR=/home/spartan/Anaconda3/envs/my_env/eigen3


I get this:-
![abcddd](https://user-images.githubusercontent.com/20614765/61968935-e13bd880-af9e-11e9-9571-99013d2f03b9.png)



Also, is path of DBOOST_INCLUDEDIR correct?

**Comment by shobhitjdpsr** [comment]
![error](https://user-images.githubusercontent.com/20614765/61969326-e3eafd80-af9f-11e9-9290-33a6aef05d21.png)

@loicland 
Finally, cmake runs with a warning.
[
CMake Warning:
  Manually-specified variables were not used by the project:

    EIGEN3_INCLUDE_DIR


-- Build files have been written to: /home/spartan/Desktop/superpoint_graph/partition/cut-pursuit/build
]

But now make has some issues:-
# include <pyconfig.h>
                       ^compilation terminated.
src/CMakeFiles/cp.dir/build.make:62: recipe for target 'src/CMakeFiles/cp.dir/cutpursuit.cpp.o' failed
make[2]: *** [src/CMakeFiles/cp.dir/cutpursuit.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/cp.dir/all' failed
make[1]: *** [src/CMakeFiles/cp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by shobhitjdpsr** [comment]
![error](https://user-images.githubusercontent.com/20614765/61969893-38db4380-afa1-11e9-9703-dfcffb9d9a8d.png)

**Comment by loicland** [comment]
[This thread](https://stackoverflow.com/questions/19810940/ubuntu-linking-boost-python-fatal-error-pyconfig-cannot-be-found) adapted to your python version.

**Comment by shobhitjdpsr** [comment]
@loicland 

No again a warning has popped up.
Please have a look

![seeeeee](https://user-images.githubusercontent.com/20614765/61974424-1c90d400-afac-11e9-83e5-a36db82de18e.png)

**Comment by shobhitjdpsr** [comment]
@loicland 

I tried various other  things to export path, but issue persists....


Please have a look 

![error2](https://user-images.githubusercontent.com/20614765/61975328-71354e80-afae-11e9-9cee-2fd02b2bb020.png)
![error23](https://user-images.githubusercontent.com/20614765/61975329-71354e80-afae-11e9-9f99-9860835006e5.png)

**Comment by shobhitjdpsr** [comment]
![take](https://user-images.githubusercontent.com/20614765/61975931-09800300-afb0-11e9-9d83-f4437e7296d2.png)


@loicland  : Have a look at this too

**Comment by shobhitjdpsr** [comment]
@loicland 

While doing cmake, I was getting following cmake-warning.

Submitting for your reference:-
![cmake warning](https://user-images.githubusercontent.com/20614765/61978870-e6f1e800-afb7-11e9-9a8f-a0a19e32f3bb.png)

**Comment by loicland** [comment]
Isn't your python version 3.7m? Try the export with this, and dont forget to erase the cmakefiles before.

**Comment by shobhitjdpsr** [comment]
@loicland 

I  am using 3.7m.

Check this

![hiii](https://user-images.githubusercontent.com/20614765/61981555-9e3e2d00-afbf-11e9-8fc2-a1671073e0f3.png)
![hii2](https://user-images.githubusercontent.com/20614765/61981553-9e3e2d00-afbf-11e9-885a-e881c8e5628c.png)
![hiii3](https://user-images.githubusercontent.com/20614765/61981551-9e3e2d00-afbf-11e9-851b-126f4eaddee9.png)

**Comment by shobhitjdpsr** [comment]
@loicland : What do you think might be causing the same and what can I do to rectify it

For your reference:-
ALso I already have libbpython3.7m.so by default in this location:-
![tttttttttttttttttttttttttt](https://user-images.githubusercontent.com/20614765/61982066-2bce4c80-afc1-11e9-882b-0722e294e326.png)

**Comment by shobhitjdpsr** [comment]
![3](https://user-images.githubusercontent.com/20614765/61982316-ff670000-afc1-11e9-8b87-e54add8d3767.png)
![2](https://user-images.githubusercontent.com/20614765/61982317-ffff9680-afc1-11e9-86e9-40358a0c3624.png)
![1](https://user-images.githubusercontent.com/20614765/61982318-ffff9680-afc1-11e9-8f21-fbfbff2df4b9.png)

**Comment by shobhitjdpsr** [comment]
@loicland 
I am using 3.7m in export, but the error persists

**Comment by loicland** [comment]
Your path has an upper case to the first letter of Anaconda which is not the case in your drive.

**Comment by shobhitjdpsr** [comment]
@loicland 
Thanks for your help!


![hii](https://user-images.githubusercontent.com/20614765/61982527-a64b9c00-afc2-11e9-8e54-9a83437b3df3.png)



Is it finally built successfully???

How can I check ?

**Comment by loicland** [comment]
Yep, it's done. Choose a dataset, open its .md file and follow the instructions.

Or run the test.py function of cut pursuit.

**Comment by shobhitjdpsr** [comment]
![tttt](https://user-images.githubusercontent.com/20614765/62086587-713e8400-b224-11e9-94df-5ba665c7f3e3.png)


@loicland  : 
In order to run the highlighted pretrained model, do we necessarily need CUDA?

I tried putting pretrained models in results/s3dis/pretrained/best    after extracting like this:_

![ttt](https://user-images.githubusercontent.com/20614765/62086660-b367c580-b224-11e9-94c5-27111dff930b.png)


Then, I put test.sh in Desktop/superpoint_graph like this:-
![hjg](https://user-images.githubusercontent.com/20614765/62086712-ddb98300-b224-11e9-8159-29a1cf53f307.png)

Then after running this on terminal I get this:-
![yyy3](https://user-images.githubusercontent.com/20614765/62086761-017cc900-b225-11e9-82b9-535d9fde8175.png)
![tt](https://user-images.githubusercontent.com/20614765/62086762-017cc900-b225-11e9-855c-f6620dd99674.png)

@loicland 
Am I doing it the right way? What to do with the errors?
Also do we necessarily need CUDA installed? aSking so as its not mentioned in requirements

**Comment by shobhitjdpsr** [comment]
@loicland

On running ./test.sh ,

I get something like this:-

**original error: libcublas.so.9.0: cannot open shared object file: No such file or directory**

Some more screenshot for your reference:-
![1](https://user-images.githubusercontent.com/20614765/62087420-430e7380-b227-11e9-9eed-a957e6c39f97.png)
![tt](https://user-images.githubusercontent.com/20614765/62087430-443fa080-b227-11e9-8a0b-842d5f15b0ed.png)

**Comment by loicland** [comment]
you can use the option `--cuda 0`

Also it seems that cupy is not found. Try to install it through conda:
```
 conda install -c anaconda cupy 
```

**Comment by nicolas-chaulet** [comment]
You won't be able to install cupy if you don't have the nvidia drivers or no GPU, which is fine. With the flag above it should all work.

**Comment by shobhitjdpsr** [comment]
@loicland  @nicolas-chaulet 
I tried installing using
 conda install -c anaconda cupy 
![install](https://user-images.githubusercontent.com/20614765/62146687-84506300-b2bb-11e9-8d88-9f09ab3ccaff.png)


Then I updated test.sh, located here:-

![abc](https://user-images.githubusercontent.com/20614765/62146727-992cf680-b2bb-11e9-8e2d-375d9f4b2f68.png)


I tried testing with test.sh containing all this:-
![0`](https://user-images.githubusercontent.com/20614765/62146771-b1047a80-b2bb-11e9-806a-10674a07dc52.png)
![00](https://user-images.githubusercontent.com/20614765/62146772-b1047a80-b2bb-11e9-92d3-3c9584b09c4e.png)


Bit I get same error:-
![abcs](https://user-images.githubusercontent.com/20614765/62148340-2160cb00-b2bf-11e9-8abc-8a0a14c0cd7e.png)
![mnb ](https://user-images.githubusercontent.com/20614765/62148356-29b90600-b2bf-11e9-966b-5531d98aa74d.png)


On doing pip freeze I get this:-
![pipppp](https://user-images.githubusercontent.com/20614765/62148554-8caa9d00-b2bf-11e9-9949-53563b4e174e.png)

I tried removing the one I did try running through through conda's cupy but I get error when running test.sh:-
![66](https://user-images.githubusercontent.com/20614765/62148612-a8ae3e80-b2bf-11e9-9c48-cf8fc8489a4a.png)
![hjvbbvb](https://user-images.githubusercontent.com/20614765/62148619-ae0b8900-b2bf-11e9-9c75-4bb5b0a22f8e.png)


Also, when I tried running through only cupy-cuda90==6.2.0 installed, I was still getting errors.(same has been attached in my previous yesterday's message)

@loicland  @nicolas-chaulet 
What would you recommend now?

**Comment by loicland** [comment]
what are the output of:
```nvcc --version```
and
```conda list```
in a terminal (in text form please, more readable than screenshot of terminals)

**Comment by shobhitjdpsr** [comment]
@loicland 

On running nvcc --version, I get:-
The program 'nvcc' is currently not installed. You can install it by typing:
sudo apt install nvidia-cuda-toolkit


Also, conda list gives the following:-

WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at /home/spartan/anaconda3/envs/my_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl    anaconda
boost                     1.67.0                   py37_4    anaconda
bzip2                     1.0.8                h7b6447c_0    anaconda
ca-certificates           2019.5.15                     0    anaconda
certifi                   2019.6.16                py37_0    anaconda
chardet                   3.0.4                    pypi_0    pypi
cudatoolkit               10.1.168                      0    anaconda
cudnn                     7.6.0                cuda10.1_0    anaconda
cupy                      6.0.0            py37hc0ce245_0    anaconda
eigen                     3.3.7                hfd86e86_0  
eigen3                    3.3.7                         0    omnia
fastrlock                 0.4                      pypi_0    pypi
future                    0.17.1                   pypi_0    pypi
h5py                      2.9.0                    pypi_0    pypi
icu                       58.2                 h211956c_0    anaconda
idna                      2.8                      pypi_0    pypi
intel-openmp              2019.4                      243    anaconda
joblib                    0.13.2                   pypi_0    pypi
libboost                  1.67.0               h46d08c1_4    anaconda
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libiconv                  1.15                 h63c8f33_5  
libstdcxx-ng              9.1.0                hdf63c60_0  
mkl                       2019.4                      243    anaconda
mkl_fft                   1.0.12           py37ha843d7b_0    anaconda
mkl_random                1.0.2            py37hd81dba3_0    anaconda
nccl                      1.3.5                cuda10.0_0    anaconda
ncurses                   6.1                  he6710b0_1  
numpy                     1.16.4                   pypi_0    pypi
numpy-base                1.16.4           py37hde5b4d6_0    anaconda
openssl                   1.1.1                h7b6447c_0    anaconda
pillow                    6.1.0                    pypi_0    pypi
pip                       19.1.1                   py37_0  
plyfile                   0.7                      pypi_0    pypi
py-boost                  1.67.0           py37h04863e7_4    anaconda
pynvrtc                   9.2                      pypi_0    pypi
python                    3.7.3                h0371630_0  
python-igraph             0.7.1.post6              pypi_0    pypi
pyzmq                     18.0.2                   pypi_0    pypi
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   pypi_0    pypi
scikit-learn              0.21.2                   pypi_0    pypi
scipy                     1.3.0                    pypi_0    pypi
setuptools                41.0.1                   py37_0  
six                       1.12.0                   pypi_0    pypi
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.29.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
torch                     1.1.0                    pypi_0    pypi
torchfile                 0.1.0                    pypi_0    pypi
torchnet                  0.0.4                    pypi_0    pypi
torchvision               0.3.0                    pypi_0    pypi
tornado                   6.0.3                    pypi_0    pypi
tqdm                      4.32.2                   pypi_0    pypi
transforms3d              0.3.1                    pypi_0    pypi
urllib3                   1.25.3                   pypi_0    pypi
visdom                    0.1.8.8                  pypi_0    pypi
websocket-client          0.56.0                   pypi_0    pypi
wheel                     0.33.4                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3

**Comment by loicland** [comment]
Hi,

pull a fresh commit, it seems like your `cuda_kernels.py` is outdated. 

@nicolas-chaulet I see you added a `pass` when cupy fail to import, but doesn't it cause an error line 42 of `cuda_kernels.py` when the import fails?

I don't see pytroch in either your pip or conda install. In a terminal, run:
```
conda install -c pytorch pytorch 
```

**Comment by shobhitjdpsr** [comment]
@loicland @nicolas-chaulet 

When trying to run test.sh containing:-
![jjj](https://user-images.githubusercontent.com/20614765/62254115-a5997800-b3bd-11e9-96fb-e7feae5ff4d3.png)



I get the following error:-
Traceback (most recent call last):
  File "learning/main.py", line 444, in <module>
    main()
  File "learning/main.py", line 159, in main
    train_dataset, test_dataset, valid_dataset, scaler = create_dataset(args)
  File "/home/spartan/Desktop/SJ/superpoint_graph/learning/s3dis_dataset.py", line 55, in get_datasets
    trainlist, testlist, validlist, scaler = spg.scaler01(trainlist, testlist, validlist=validlist)
  File "/home/spartan/Desktop/SJ/superpoint_graph/learning/spg.py", line 53, in scaler01
    edge_feats = np.concatenate([ trainlist[i][3] for i in range(len(trainlist)) ], 0)
ValueError: need at least one array to concatenate
![tyty](https://user-images.githubusercontent.com/20614765/62254133-b649ee00-b3bd-11e9-96ae-bb419758465f.png)

Also, I tried searching in s3dis.py, it is searching .h5 files, but there are no .h5 files in stanford dataset, see:-
![g](https://user-images.githubusercontent.com/20614765/62254148-c5c93700-b3bd-11e9-855e-350390a7e81b.png)

**Comment by shobhitjdpsr** [comment]
what can b done to get rid of this???

**Comment by loicland** [comment]
Your S3DIS_DIR folder should have a `/data` folder, a `/features`folder, a `superpoint_graphs` folder and a `/parsed` folder. All of these contains folder by area, and inside a .h5 file per room. Follow the instructions (partition and parsing) and you should get there.

**Comment by shobhitjdpsr** [comment]
![hhhhhhhh](https://user-images.githubusercontent.com/20614765/62328882-f40c4c80-b479-11e9-936c-df76920cb580.png)

**Comment by whuhxb** [comment]
> In ply_c while doing MAKE, I am getting following error:
> 
> [ 50%] Building CXX object CMakeFiles/ply_c.dir/ply_c.cpp.o /home/spartan/Desktop/superpoint_graph/partition/ply_c/ply_c.cpp:4:23: fatal error: Eigen/Dense: No such file or directory #include <Eigen/Dense> ^ compilation terminated. CMakeFiles/ply_c.dir/build.make:62: recipe for target 'CMakeFiles/ply_c.dir/ply_c.cpp.o' failed make[2]: *** [CMakeFiles/ply_c.dir/ply_c.cpp.o] Error 1 CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ply_c.dir/all' failed make[1]: *** [CMakeFiles/ply_c.dir/all] Error 2 Makefile:83: recipe for target 'all' failed make: *** [all] Error 2 (my_env) spartan@spartan-

How to solve this compilation error? Thanks.
