### ISSUE TITLE
visualize for vkitti

### ISSUE THREAD

**Issue by kxhit** [loicland/superpoint_graph#189]
Hi! @loicland 
I follow the vkitti3d.md and run `python partition/visualize.py --dataset vkitti --ROOT_PATH $VKITTI3D_DIR --res_file 'results/vkitti/best/cv1/predictions_test' --file_path '01/0001_00000' --output_type ifprs`. I got error below:

`writing the RGB file...
writing the features file...
writing the partition file...
writing the prediction file...
Traceback (most recent call last):
  File "partition/visualize.py", line 99, in <module>
    prediction2ply(ply_file + "_pred.ply", xyz, pred_full+1, n_labels,  args.dataset)
  File "/media/work/3D/superpoint_graph/partition/provider.py", line 63, in prediction2ply
    color[np.where(prediction == i_label), :] = get_color_from_label(i_label, dataset)
  File "/media/work/3D/superpoint_graph/partition/provider.py", line 162, in get_color_from_label
    raise ValueError('Unknown dataset: %s' % (dataset))
ValueError: Unknown dataset: vkitti`

I find that there is no implementation for vkitti in `get_color_from_label` in provider.py.

 Could you help me? Thanks!

**Comment by kxhit** [comment]
Fixed. Closed.
