### ISSUE TITLE
Error in training AttributeError: 'Program' object has no attribute '_program @ acc, loss, oacc, avg_iou = train() in learning/main.py"

### ISSUE THREAD

**Issue by chowkamlee81** [loicland/superpoint_graph#51]
Hi,
Currently using 0.3.1 pytorch
a) Did partition of semantic 3d data using
python partition/partition.py --dataset sema3d --ROOT_PATH /home/administrator/Documents.orig/FileSystem/Server_Code/sematic3d --voxel_width 0.05 --reg_strength 0.8 --ver_batch 5000000
b) reorganize point clouds into superpoints by
python learning/sema3d_dataset.py --SEMA3D_PATH /home/administrator/Documents.orig/FileSystem/Server_Code/sematic3d

**But got the error below: Kindly help**

Epoch 0/500 (/home/administrator/Documents.orig/Kumar_FileSystem/results/sema3d/trainval_best):
  0%|                                                                         | 0/7 [00:00<?, ?it/s]Traceback (most recent call last):
  File "learning/main.py", line 387, in <module>
    main()
  File "learning/main.py", line 286, in main
    acc, loss, oacc, avg_iou = train()
  File "learning/main.py", line 184, in train
    outputs = model.ecc(embeddings)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/administrator/Documents.orig/FileSystem/Server_Code/sematic3d/superpoint_graph-release/learning/graphnet.py", line 97, in forward
    input = module(input)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/administrator/Documents.orig/FileSystem/Server_Code/sematic3d/superpoint_graph-release/learning/modules.py", line 54, in forward
    input = ecc.GraphConvFunction(nc, nc, idxn, idxe, degs, degs_gpu, self._edge_mem_limit)(hx, weights)
  File "/home/administrator/Documents.orig/FileSystem/Server_Code/sematic3d/superpoint_graph-release/learning/ecc/GraphConvModule.py", line 67, in forward
    cuda_kernels.conv_aggregate_fw(output.narrow(0,startd,numd), products.view(-1,self._out_channels), self._degs_gpu.narrow(0,startd,numd))
  File "/home/administrator/Documents.orig/FileSystem/Server_Code/sematic3d/superpoint_graph-release/learning/ecc/cuda_kernels.py", line 120, in conv_aggregate_fw
    function, stream = get_kernel_func('conv_aggregate_fw_kernel_v2', conv_aggregate_fw_kernel_v2(), get_dtype(src))
  File "/home/administrator/Documents.orig/FileSystem/Server_Code/sematic3d/superpoint_graph-release/learning/ecc/cuda_kernels.py", line 33, in get_kernel_func
    prog = Program(ksrc.encode('utf-8'), (kname+dtype+'.cu').encode('utf-8'))
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/pynvrtc/compiler.py", line 52, in __init__
    include_names)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/pynvrtc/interface.py", line 200, in nvrtcCreateProgram
    c_char_p(encode_str(src)), c_char_p(encode_str(name)),
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/pynvrtc/interface.py", line 54, in encode_str
    return s.encode("utf-8")
AttributeError: 'bytes' object has no attribute 'encode'
Exception ignored in: <bound method Program.__del__ of <pynvrtc.compiler.Program object at 0x7f3c4c640c50>>
Traceback (most recent call last):
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/pynvrtc/compiler.py", line 56, in __del__
    self._interface.nvrtcDestroyProgram(self._program)
AttributeError: 'Program' object has no attribute '_program

**Comment by chowkamlee81** [comment]
solved by using  
replacing line 3̶5̶ 33 of /learning/ecc/cuda_kernels.py by

prog = Program(ksrc, (kname+dtype+'.cu'))

Closing the issue
