### ISSUE TITLE
Random Runtime Illegal Memory Access Error at training S3DIS Dataset

### ISSUE THREAD

**Issue by lufi0401** [loicland/superpoint_graph#81]
Hi, 

I'm following the instructions at [training S3DIS](https://github.com/loicland/superpoint_graph#training) to reproduce the result and encountered random illegal memory access error during training.

Previous steps were completed without error. I was running the following command when the error would occur ~70% of the times:
```
for FOLD in 1 2 3 4 5 6; do 
  CUDA_LAUNCH_BLOCKING=1 \
  CUDA_VISIBLE_DEVICES=0 \
  python learning/main.py \
  --dataset s3dis \
  --S3DIS_PATH $S3DIR_DIR \
  --cvfold ${FOLD} \
  --epochs 350 \
  --lr_steps '[275,320]' \
  --test_nth_epoch 50 \
  --model_config 'gru_10_0,f_13' \
  --ptn_nfeat_stn 14 \
  --nworkers 2 \
  --odir $S3DIR_DIR/results/s3dis/best/cv; 
done
```

Can anyone help resolving the issue?

Thanks.

---

The environment was setup using conda with:
- Ubuntu 16.04
- GeForce GTX 1080 Ti with CUDA 9 and Driver 410.79
- Conda Env with python3.6 and pytorch 0.3.1.post2

The error message is as follows:
```
  File "learning/main.py", line 387, in <module>
    main()
  File "learning/main.py", line 286, in main
    acc, loss, oacc, avg_iou = train()
  File "learning/main.py", line 187, in train
    loss.backward()
  File "/home/.../anaconda3/envs/spg/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/.../anaconda3/envs/spg/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
  File "/.../superpoint_graph/learning/ecc/GraphConvModule.py", line 102, in backward
    cuda_kernels.conv_aggregate_bw(grad_products, grad_output.narrow(0,startd,numd), self._degs_gpu.narrow(0,startd,numd))
  File "/.../superpoint_graph/learning/ecc/cuda_kernels.py", line 138, in conv_aggregate_bw
    block=(CUDA_NUM_THREADS,1,1), grid=(GET_BLOCKS(w),n//blockDimY+1,1), stream=stream)
  File "cupy/cuda/function.pyx", line 148, in cupy.cuda.function.Function.__call__
  File "cupy/cuda/function.pyx", line 130, in cupy.cuda.function._launch
  File "cupy/cuda/driver.pyx", line 228, in cupy.cuda.driver.launchKernel
  File "cupy/cuda/driver.pyx", line 81, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered

Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 192, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 81, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 192, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 81, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 192, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 81, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 192, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 81, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

**Comment by mys007** [comment]
Thanks for the report. I'm afraid this can be the same error as described in https://github.com/mys007/ecc/issues/1 , which I have not been able to resolve so far: it's been very random and hard to reproduce. It would likely require a rewrite of the cuda part. The best I can advise you now is to try to restart the training with `--resume RESUME` argument...

**Comment by loicland** [comment]
Hi,

I have a similar issue on one of my 3 rigs (ubuntu 16.04, 1080Ti, Cuda8.0, Drivers 384.111), which cause crashes every 5-6 hours. Only way around it so far is what @mys007 suggested:
```
python learning/main.py  --OPTIONS options
for ATTEMPT in 1 2 3; do \
python learning/main.py --OPTIONS options --resume RESUME; \
done
```

It's dirty but works, and the inference is stable as far as I can tell.
